DROP TABLE IF EXISTS notes cascade;

--NOTE TABLE
CREATE TABLE notes (
  id SERIAL PRIMARY KEY,
  note TEXT,
  done BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
)